package pl.polsl.lab.snake.model;

/**
 * Data containing class. Stores generated game and user input about generated moves
 * @version 1.0
 * @author Michał Urbańczyk
 */
public class Snake {

    private int howManyMovesLeft;   // moves inputed by user
    private String generatedGame;   // string containing snake game generated by program
    public void setHowManyMovesLeft(int howManyMovesLeft) {
        this.howManyMovesLeft = howManyMovesLeft;
    }

    public int getHowManyMovesLeft() {
        return howManyMovesLeft;
    }

    public void decrementMoves(){
        howManyMovesLeft -= 1;
    }

    public String getGeneratedGame(){
        return generatedGame;
    }
    public void setGeneratedGame(String generatedGame){
        this.generatedGame = generatedGame;
    }
}
